### ISSUE TITLE
Toast message units in 7 days view

### ISSUE THREAD

**Issue by DocSniper** [fadelakin/vortex#2]
When I click a day in "This Week's Weather" view the toast message units are F even if I switch to C.

**Comment by fadelakin** [comment]
@sniperle that's an easy fix. i'll add it into the coming update.

**Comment by fadelakin** [comment]
@sniperle this has been fixed in the 2.0.2 release that i just pushed. it all depends on when fdroid adds it so you can get the update. :smile:
