### ISSUE TITLE
24 hour time

### ISSUE THREAD

**Issue by DocSniper** [fadelakin/vortex#3]
Can you please add an option for 24 hour (military) time ? Thanks

And maybe some future options require a switch for imperial vs metrical units.  ;-)

**Comment by fadelakin** [comment]
@sniperle I'll look into it. But as I'm incredibly busy right now, solving the specific bugs and implementing the new features might take a while so I can't specify a specific date as to when I'll push things live.

**Comment by fadelakin** [comment]
@sniperle does military time have PM and AM? I don't know if I should display it 23PM, 2 AM and so on or just 23, 24, 25. I was thinking instead of PM and AM, I would switch it to something like 23:00 or 2:00 or 13:00.

what do you think?

**Comment by DocSniper** [comment]
It doesn't have am and pm, just only the time in 24 hour notation, like you wrote: 2:47 or 02:47 or 21:56

**Comment by fadelakin** [comment]
@sniperle i implemented military time and it'll come in the next update which should be sometime this week. if you tap the settings icon, you will see an option for it.

**Comment by DocSniper** [comment]
Thanks :-)
